### ISSUE TITLE
Accurate block placement not working on server

### ISSUE THREAD

**Issue by Bran99** [maruohon/tweakeroo#100]
tweakeroo-fabric-1.16.3-0.10.0-dev.20200913.175041.jar
server: Self hosted running Fabric on DigitalOcean
minecraft version: 1.16.3

I'm running a self hosted server on a DigitalOcean droplet.  I'm running Fabric on the server as well as locally.  I can see the block getting placed facing a different way and then it quickly rotates to the direction it would normally be placed if I weren't using accurate block placement.

**Comment by maruohon** [comment]
Do you have either QuickCarpet or FabricCarpet with CarpetExtra on the server, with the `accurateBlockPlacement` Carpet rule enabled? (This support will move to my Servux mod at some point in the future.) The block rotations for most blocks won't work without a server-side mod handling the request for a custom facing.

**Comment by Bran99** [comment]
I only had FabricCarpet, not CarpetExtra.  I installed CarpetExtra and it works perfectly.  Thank you!

**Comment by brookeab27** [comment]
hey, when i try to enable this in my other server /carpet doesn't show accurate block placement, please help as i just want to use flexible block placement and i am going insane trying to find the fix

**Comment by maruohon** [comment]
Do you also have CarpetExtra on the server? That rule is not in the base FabricCarpet mod.

**Comment by brookeab27** [comment]
> 

yes

**Comment by brookeab27** [comment]
do i need to have it in my client ?

**Comment by maruohon** [comment]
No, Carpet and CarpetExtra are only needed on the server side for this. Is CarpetExtra actually running on the server, is it in the mod list in the console/log when the server starts up? Which MC version are you in, and which CarpetExtra version does the server have?

**Comment by brookeab27** [comment]
> No, Carpet and CarpetExtra are only needed on the server side for this. Is CarpetExtra actually running on the server, is it in the mod list in the console/log when the server starts up? Which MC version are you in, and which CarpetExtra version does the server have?

i'm sorry i downloaded it and forgot to add it to the server, i am a bit silly. have a good day and thanks for the help
