### ISSUE TITLE
Method overwrite conflict for getSlotIndex

### ISSUE THREAD

**Issue by calloatti** [maruohon/tweakeroo#11]
itemscroller-fabric-1.14.4-0.15.0-dev.20190720.190250.jar
tweakeroo-fabric-1.14.4-0.9.10.jar

[main/WARN]: Method overwrite conflict for getSlotIndex in mixins.tweakeroo.json:IMixinSlot, previously written by fi.dy.masa.itemscroller.mixin.IMixinSlot. Skipping method.

https://github.com/maruohon/itemscroller/issues/25

**Comment by maruohon** [comment]
This is only a warning, but the 0.10.0 versions also removed this Mixin as it wasn't really needed anyway. SO this is fixed as of commit 0e710258c.
