### ISSUE TITLE
Chat Timestamps not working

### ISSUE THREAD

**Issue by ImmortalZypther** [maruohon/tweakeroo#114]
I'm currently on the official v1.16.3 Minecraft release with the mod version of 1.16.4-0.10.0-dev.20201103.184154
I've enabled tweakChatTimestamp but there are no timestamps in chat.

![image](https://user-images.githubusercontent.com/21045587/98450941-36a5e580-210f-11eb-8971-06fbed250934.png)

Is there another setting to enable or some other option to configure?

**Comment by maruohon** [comment]
That is the only toggle option required. The time format is in Generic configs, and by default it should it should include the hour, minute and second. It is working for me in the latest build. Note that it doesn't add the time stamp to already existing messages, only messages received/printed after enabling the tweak.

So if it's not working, and you have another chat related mod, such as some twitch integration mod, then that might be conflicting.
![chat](https://user-images.githubusercontent.com/2331050/98452529-b1472300-2158-11eb-8c30-00d5594684d4.png)

**Comment by ImmortalZypther** [comment]
Ah, understood.

Sorry for not properly going through my mod list before submitting an issue.

**Comment by maruohon** [comment]
Let me know if you find the conflict, so I know for possible similar questions in the future. And maybe I can even change the implementation to make it compatible, depending on what it conflicts with and how they do stuff.
