### ISSUE TITLE
[Idea] Waypoint System

### ISSUE THREAD

**Issue by Sar4h-3** [maruohon/tweakeroo#115]
I think it would be useful to have some kind of Waypoint system. I am currently exploring the new snapshot and want to have some kind of orientation without writing interesting coords down externally. I was debaiting on writing this in the Minihud Github, but i felt it is better suited here

**Comment by 0xfeeddeadbeef** [comment]
Minimap and worldmap mods are better suited for this task. I'd suggest [VoxelMap](https://www.curseforge.com/minecraft/mc-mods/voxelmap), [Just Map](https://www.curseforge.com/minecraft/mc-mods/just-map-unlimited) or [Xaero's World Map](https://www.curseforge.com/minecraft/mc-mods/xaeros-world-map).

**Comment by maruohon** [comment]
Yep in general this is better suited for minimap mods. But I have also considered adding it to MiniHUD, as it is kind of a type of "information output" which is mostly what MiniHUD does (information output and rendering of information).
