### ISSUE TITLE
MultiMC crashes when launching 1.14.3

### ISSUE THREAD

**Issue by Zulgeteb** [maruohon/tweakeroo#12]
ZulgetebToday at 17:51
https://paste.ee/p/52uIn
Paste.ee
View Paste 52uIn
Paste.ee - View Paste 52uIn

1.14.3 is still crashing, replaced the 207 api with the 200 version and replaced light overlay with 3.3.1

modmuss50Today at 18:00
tweakeroo is failing to apply its mixin

ZulgetebToday at 18:18
what to do about that

calloattiToday at 18:23
open an issue here: https://github.com/maruohon/tweakeroo/issues

**Comment by Zulgeteb** [comment]
removing OptiFabric made it work but i want to have Optifine too

**Comment by maruohon** [comment]
I believe this was fixed in 0.9.9. I think you should be able to use the 0.9.9 version for 1.14.4 on 1.14.3 as well, however the latest 0.9.10 version probably won't work because it has a 1.14.4 specific fix for vanilla.

**Comment by Zulgeteb** [comment]
I placed OptiFabric back and removed OptiFine 1.14.3 HD U F2 , downlaoed the older version OptiFine 1.14.3 HD U F1 and placed that.
Now its working again.
