### ISSUE TITLE
Tweakeroo causing game crash when generating world 1.16.4

### ISSUE THREAD

**Issue by ghost** [maruohon/tweakeroo#120]
When I click the "customize" button under the superflat setting in the world maker, Tweakeroo causes the game to crash

**Comment by NikitaCartes** [comment]
Crash report: https://pastebin.com/8q5DpyEW
tweakeroo-fabric-1.16.4-0.10.0-dev.20201103.184154
malilib-fabric-1.16.4-0.10.0-dev.21+arne.1
fabric-api-0.25.1+build.416-1.16

**Comment by maruohon** [comment]
I uploaded a new version which fixes this crash.
