### ISSUE TITLE
Crashes when attempting to customize superflat world

### ISSUE THREAD

**Issue by EloCode** [maruohon/tweakeroo#130]
Every time I try to enter the menu to create a custom superflat world the game crashes. It happens only if, and if only twekeroo is enabled. I'll attach the crash report
[crash-2020-11-25_20.59.17-client.txt](https://github.com/maruohon/tweakeroo/files/5599033/crash-2020-11-25_20.59.17-client.txt)

**Comment by maruohon** [comment]
This should be fixed in the 2020-11-10 build.

https://www.curseforge.com/minecraft/mc-mods/tweakeroo/files/3107606

**Comment by EloCode** [comment]
Oh your right, i thought i had most up to date version already. Well thanks
