### ISSUE TITLE
Freedom won't let me move around

### ISSUE THREAD

**Issue by nbaddorf** [maruohon/tweakeroo#133]
Hi, I am trying to use the freecam with your mod. I have set the activate button to B. When I click B, my screen changes slightly, and I get the notification that freecam is on, but I can not move. Any help is appreciated.

**Comment by maruohon** [comment]
The only reason for this I've heard thus far is having another mod such as another free camera mod installed, which interferes with Tweakeroo's free camera implementation.

**Comment by nbaddorf** [comment]
Well, you hit that spot on! Thanks so much for your help! This mod is amazing!
