### ISSUE TITLE
 Disabling tile entity rendering (TweakNo Toggles) does not render the chest picture button in the inventory.

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [maruohon/tweakeroo#134]
Minecraft 1.16.4
malilib-fabric-1.16.4-0.10.0-dev.21+arne.2
tweakeroo-fabric-1.16.4-0.10.0-dev.20201122.174805

Disabling tile entity rendering (TweakNo Toggles) does not render the chest picture button in the inventory.

Expected behaviour: it renders it normally, and only unrenders the item and the block.

How to reproduce:
Turn on 'disableTileEntityRendering' in 'TweakNo Toggles'.
Observe the change.

![image](https://user-images.githubusercontent.com/68545280/100546646-5934a580-325a-11eb-8e0e-1eca1d5a71ac.png)
![image](https://user-images.githubusercontent.com/68545280/100546659-6f426600-325a-11eb-940e-1a5d64cc58f3.png)

**Comment by maruohon** [comment]
This uses the same renderer as the chest item, so it's not really possible (without ugly hacks) to make this one thing render while all the other cases don't. The actual annoying thing is that these items even use the tile entity renderer instead of a regular model...

**Comment by DragonEggBedrockBreaking** [comment]
f
