### ISSUE TITLE
'disableTileEntityRendering' doesn't unrender all tile entities.

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [maruohon/tweakeroo#135]
Minecraft 1.16.4
malilib-fabric-1.16.4-0.10.0-dev.21+arne.2
tweakeroo-fabric-1.16.4-0.10.0-dev.20201122.174805

'disableTileEntityRendering' doesn't unrender all tile entities. (This list is from https://minecraft.gamepedia.com/Block_entity and checked with NBT Explorer)

Expected behaviour: All of them will unrender.

How to reproduce:
1) place these blocks in your world
2) set 'disableTileEntityRendering' to 'true'
3) observe

![image](https://user-images.githubusercontent.com/68545280/100547377-52a82d00-325e-11eb-8eec-3eedf41f62bd.png)
![image](https://user-images.githubusercontent.com/68545280/100547394-6784c080-325e-11eb-94bf-d92c4b9c2869.png)

Special cases:
![image](https://user-images.githubusercontent.com/68545280/100547425-8f742400-325e-11eb-849b-4d2336e8f9f5.png)
![image](https://user-images.githubusercontent.com/68545280/100547427-98fd8c00-325e-11eb-9de9-4aa1311a6e5a.png)

**Comment by maruohon** [comment]
This only disables the "Tile Entity Special Renderers". It does not disable rendering of normal static block models. Some blocks that have a tile entity use a combination of both, such as the enchanting table and the beacon (the rotating book and the beam use the special renderer). So this is not even meant to disable all rendering for all blocks that simply have a tile entity.

The main point is to disable the dynamic renderer. There are basically two use cases for this, which are that the dynamic renderer is a lot slower than the pre-baked chunk meshes where the normal static models end up in. And the second is that in some cases (mostly with some modded blocks) there are sometimes rendering bugs that crash the client in the rendering of some of the special renderers, so this would allow you to avoid the crash and remove the offending block.

**Comment by DragonEggBedrockBreaking** [comment]
Ah, ok.
