### ISSUE TITLE
Typographical Error In Tooltip

### ISSUE THREAD

**Issue by WolfPack30156** [maruohon/tweakeroo#14]
#### Issue description
In the configuration menu the tooltip message / on-hover message for tweakLavaVisibility has a typo in the displayed text.

#### Steps to reproduce the issue

1.  Load into a SMP world
2.  Press X+C to open config
3.  Click into Tweak Toggles
4.  Scroll until tweakLavaVisibility is visible
5.  Hover over tweakLavaVisibility 

#### What's the expected result?

- Display a tooltip with the following text 'If enabled and the player has a Respiration helmet and/or Water Breathing active, the lava fog is greatly reduced.'

#### What's the actual result?

- Displays a tooltip with the following text ''If enabled and the player has a Respiration helmet and/or Wahter Breathing active, the lava fog is greatly reduced.'

#### Additional details / screenshot

- ![In-Game Screenshot](https://user-images.githubusercontent.com/50341740/63207972-c2f86280-c09c-11e9-8253-5e6a582d60e8.png)

**Comment by Anunayj** [comment]
haha
btw What should one do when he finds a problem like this. What is better a Pull request or a issue?

**Comment by WolfPack30156** [comment]
Over all to change one line, I know how to do an issue, still learning
GitHub on pr.

**Comment by Anunayj** [comment]
I opened a pull request for this: https://github.com/maruohon/tweakeroo/pull/15 , if that is what one should do.

**Comment by WolfPack30156** [comment]
Thanks, I guess we will have to wait for @maruohon to accept the merge change. 

I appreciate your help @Anunayj.

**Comment by maruohon** [comment]
I think in general for trivial stuff like typo fixes, especially if the user discovering it is already on any of the Discord servers I'm on, I would prefer a ping on Discord to let me know about it. Pull Requests and merges just create a lot more noise in the commit history for very minor changes. But anyway, thanks for letting me know about this... :D

**Comment by WolfPack30156** [comment]
Apologies for that, I am not in your discord.

Thank you for your time and response!
