### ISSUE TITLE
I'm using tweakeroo for 1.16.1 and this appears with fabric

### ISSUE THREAD

**Issue by ghost** [maruohon/tweakeroo#140]
![image](https://user-images.githubusercontent.com/76539725/103043250-fed9ec80-455a-11eb-9246-d8b5c5757961.png)

**Comment by maruohon** [comment]
Like the error message says, Tweakeroo requires the malilib mod, which is currently not installed.

**Comment by ghost** [comment]
> Like the error message says, Tweakeroo requires the malilib mod, which is currently not installed.

Can you give me the link, please.

**Comment by maruohon** [comment]
It's linked on the Tweakeroo page on CurseForge, and also from the required libraries section on the individual file's page.

https://www.curseforge.com/minecraft/mc-mods/malilib

**Comment by ghost** [comment]
I'm new to Github, you can close this already.
