### ISSUE TITLE
going into FreeCam doesn't load more chunks (is this normal?)

### ISSUE THREAD

**Issue by ghost** [maruohon/tweakeroo#143]
Minecraft 1.16.4, only using tweakeroo and malilib with fabric.
I previously used only Optifine, and then only Sodium, and I tried to use Sodium with tweakeroo and malilib. Then this issue happened. I remove Sodium from the mods folder and tested FreeCam again (only tweakeroo and malilib). It didn't work.
<img width="848" alt="Screen Shot 2020-12-29 at 11 33 46 AM" src="https://user-images.githubusercontent.com/63276837/103254841-51d3f980-49ca-11eb-9c64-ef2de10050c9.png">

I deleted optionsshaders.txt but that does nothing.
Is this normal?
How do I fix this?

**Comment by maruohon** [comment]
The main point of the Free Camera feature is that it gives you a freely movable camera perspective, while the actual player stays in place. And the chunk loading is based on the player's position on the server side. So yes this is intended.
