### ISSUE TITLE
Simulated held down button

### ISSUE THREAD

**Issue by UltraBlackLinux** [maruohon/tweakeroo#147]
Hey, there, it's me again,
I just wanted to say, it would be really nice, if tweakeroo actually had a mode to really hold down the attack/use button. Not click in specified intervals. (Anticheat compatibility lol). Also please make a discord server...
Thanks!

**Comment by maruohon** [comment]
It does have the `holdAttack` and `holdUse` tweaks.

And I do have my own Discord server (https://discord.gg/2FgywHj), plus most of my client mod support and feedback happens on the `#masas-mods` channel on the SciCraft Discord: https://discord.gg/scicraft

**Comment by UltraBlackLinux** [comment]
@maruohon Yeah, I know, that there are tweaks for it, my request is, to not click in selected intervals, and rather let minecraft do it:
![Screenshot_20210108_124915](https://user-images.githubusercontent.com/62404294/104012389-054da280-51b0-11eb-952f-683037adc5ca.png)

**Comment by UltraBlackLinux** [comment]
I am just a bit scared about this, to say the least. I realised, that the hold use seems faster, than holding down the right click button...

**Comment by maruohon** [comment]
If you are on a server that has very strict rules about stuff like this, then you probably shouldn't be using Tweakeroo at all. Or only purely visual stuff like some of the rendering options or shulker box preview etc

And I meant these first two options:
![image](https://user-images.githubusercontent.com/2331050/104021592-b6ac0280-51c7-11eb-9029-6bf5c04120e2.png)
