### ISSUE TITLE
Feature request: Entity search

### ISSUE THREAD

**Issue by UltraBlackLinux** [maruohon/tweakeroo#149]
I'd love to have the ability, to search for mobs, and also with their nametag...
Thanks!

**Comment by eatmyvenom** [comment]
Earth computers [client commands](https://github.com/Earthcomputer/clientcommands) mod has a feature like this. 

You should probably look to see if other mods have a feature you are looking for before you go and start asking a dev to add it to their mod.

**Comment by UltraBlackLinux** [comment]
@eatmyvenom This seems like a mod for singleplayer 2b2t tho
lol
EDIT: I looked at this mod and I barely like it. It uses vanilla command syntax and is really only commands.

**Comment by maruohon** [comment]
This is outside the scope of this mod. The TellMe mod also already has this feature (except for searching by name).

**Comment by UltraBlackLinux** [comment]
@maruohon well, if there is no practical way to search entities by name, then I will close this...

**Comment by maruohon** [comment]
It's possible, but I'm not going to add it to Tweakeroo as it does not belong there, it's totally different than any of the other features. I might add searching by name to TellMe ,as it already has the entity search command anyway, it just needs to be filtered differently.
