### ISSUE TITLE
You cant move / break block / place block while in free cam

### ISSUE THREAD

**Issue by barraIhsan** [maruohon/tweakeroo#155]
Yea, i know its work as intended. But the problem is you cant break block when you are like auto mine (Baritone). It so much sense because you can still mining when open gui when using auto mine. So maybe the player keep mining / moving / placing block but the free cam is free look

**Comment by maruohon** [comment]
Does it work if you toggle on the `freeCameraPlayerInputs` option/hotkey? But other than that, the way the mod tries to reliably prevent all the player inputs then probably also catches the Baritone inputs. The only way to "fix" that would be to make the input cancellation less robust and only try to catch actual keyboard/mouse inputs and not the actual use packets. Personally I don't like that idea.

**Comment by barraIhsan** [comment]
yes it work with freeCameraPlayerInput
