### ISSUE TITLE
Incompatible with Carpet Mod 1.4.25

### ISSUE THREAD

**Issue by BeetMacol** [maruohon/tweakeroo#167]
17 days ago [my pull request with three nice structure block additions](https://github.com/gnembon/fabric-carpet/pull/664) for Carpet was merged. One of the options I added there was `structureBlockLimit`, and unfortunately, after it was released in the latest Carpet Mod version, Andrew54757 noticed it crashes with Tweakeroo.  
More specifically Tweakeroo's `TWEAK_STRUCTURE_BLOCK_LIMIT` uses a mixin to change the limits of the structure blocks using `@ModifyConstants` and I did exactly the same thing for carpet's `structureBlockLimit`. My solution to that problem was a bit better though because I also got rid of the 256 upper limit and obviously made it work on dedicated servers (according to the description of https://github.com/maruohon/tweakeroo/commit/70af1736e2b25b702196f14fbf1b61554a8f3d03, on Tweakeroo it only works in singleplayer).  
I wanted to try the Tweakeroo's solution in-game but it didn't work for me, not sure if I did everything right.

**Comment by maruohon** [comment]
This was already fixed in the 2021-02-04 build of Tweakeroo. (On my server there are even a few builds after that already.)

**Comment by BeetMacol** [comment]
Is it a temporary fix or a proper solution? Should I just close this issue?

**Comment by maruohon** [comment]
What constitutes a temporary fix vs. proper solution? I changed the `@Override` into an `@Inject`. So it does not crash with Carpet anymore, but both mods can co-exist now.

**Comment by BeetMacol** [comment]
Again, I can't get Tweakeroo's limit change to work. It always brings the values back to 46 even if the tweak is enabled and set to 256.

**Comment by maruohon** [comment]
Oh hah true, the tweak wasn't actually working, because my `@ModifyConstant` was still using the old value of 32. I fixed that too now.

**Comment by Jroid8** [comment]
Since this issue is fixed in the latest version, can someone close this issue?
