### ISSUE TITLE
Crashing When going from Nether to Overworld on Death

### ISSUE THREAD

**Issue by Today20092** [maruohon/tweakeroo#173]
Not exactly sure what the reasoning is here or what other information you need, but I am crashing when I die in the nether.

[crash-2021-02-17_23.44.30-client.txt](https://github.com/maruohon/tweakeroo/files/6000314/crash-2021-02-17_23.44.30-client.txt)

https://gist.githubusercontent.com/natanfudge/1a2690190dd3b3d13e1c6e9cc470a1d0/raw/a28e7f237a07a688c62a1878e68c074e20235f12/crash.txt

**Comment by maruohon** [comment]
Try if the latest build from here fixes it: https://masa.dy.fi/mcmods/client_mods/?mcver=1.16.4

It might be related to server ping, as I don't crash with the older version either, at least in single player.

**Comment by Today20092** [comment]
> Try if the latest build from here fixes it: https://masa.dy.fi/mcmods/client_mods/?mcver=1.16.4
> 
> It might be related to server ping, as I don't crash with the older version either, at least in single player.

Just got it and tried it, no crash. Will send another crash report if it happens again! Thank you # #
