### ISSUE TITLE
DisableInventoryEffectRendering doesn't work

### ISSUE THREAD

**Issue by Akorian** [maruohon/tweakeroo#176]
I am using Fabric for 1.16.5. Everything in this GREAT mod is working as far as aI tested except for the DisableInventoryEffectRendering. It doesn't remove effects from my Inventory GUI. Since I am using a mod to display my effects, this is pretty annoying. 
I tried using a toggle button but it didn't work.
![image](https://user-images.githubusercontent.com/37375458/109058670-92f33c00-76e3-11eb-8896-919e2849021b.png)

**Comment by maruohon** [comment]
I uploaded a new build with a fix here for now: https://masa.dy.fi/mcmods/client_mods/?mcver=1.16.4

**Comment by Akorian** [comment]
Nice! Works now!
