### ISSUE TITLE
[IDEA] Tweak: NoNausea

### ISSUE THREAD

**Issue by platinorum** [maruohon/tweakeroo#177]
The nausea/nether portal wobbling is annoying...
I know, there's an option for that in the Accessibility Settings, but with that there's a green vignette instead. I think this tweak would fit into the mod. :)

**Comment by maruohon** [comment]
There is now a  `disableNauseaEffect` option in the latest build here: https://masa.dy.fi/mcmods/client_mods/?mcver=1.16.4
