### ISSUE TITLE
Going into freecam and then doing /kill @s on a singleplayer world makes the game freak out

### ISSUE THREAD

**Issue by bomba1749** [maruohon/tweakeroo#181]
If you go into freecam and then kill yourself, on a singleplayer world, it freaks out in a way i can't really describe

**Comment by maruohon** [comment]
Which mod version are you using? This was supposed to be fixed already in a recent-ish version for 1.16.4.

**Comment by bomba1749** [comment]
tweakeroo-fabric-1.16.4-0.10.0-dev.20201110.132827

**Comment by bomba1749** [comment]
oops i just checked and my version is indeed an older version. Sorry!
