### ISSUE TITLE
Player list invisible with OF

### ISSUE THREAD

**Issue by MeeniMc** [maruohon/tweakeroo#189]
## Problem

When using Tweakeroo at the same time as Optifine, the player list is invisible in some cases: 

1. When only one player is present, both the 'keybind (default tab' and  the always show option of tweakeroo fail to render the player list.
2. When more than one player is present, the keybind works, but the always show option still doesn't render the player list.

This is especially annoying when using Carpet /log command to show TPS or wool block counters.

## Setup

* MC 1.16.5
* Fabric API 0.30.3
* Optifabric 1.9.6
* OF HD_U_G8_pre2
*  Tweakeroo 20210303
(no other mods)

Prior versions also had that same bug, since at least November last year (maybe earlier, that's when I started noticing).

There is no issue w/o OF.

**Comment by kkellogg378** [comment]
Sadly still an issue :/

**Comment by MeeniMc** [comment]
I am not using OF anymore so I don't know if this is still going on. Someone that has a stake in the game should track this problem if it is still present.
