### ISSUE TITLE
MultiMC 1.14.4 crashes while launching

### ISSUE THREAD

**Issue by Philipp766** [maruohon/tweakeroo#19]
if i activate tweakeroo it crashes, if i disable it, it runs normally
     https://pastebin.com/xtUYsp2X

**Comment by maruohon** [comment]
This is fixed in FabricCarpet 1.0.6candidate, which is linked in SciCraft Discord some time yesterday on the #carpet-mod channel.

**Comment by Philipp766** [comment]
yup, works, thanks
