### ISSUE TITLE
BUG with optifabric

### ISSUE THREAD

**Issue by MaialinoPic** [maruohon/tweakeroo#201]
when i use optifabric with tweakeroo and i activatet the freecam, my player fall down and i can pass trought walls with this glitch

**Comment by maruohon** [comment]
This was fixed some time ago, update your Tweakeroo to the latest version.

**Comment by Dir7y** [comment]
its happening with the latest release

**Comment by maruohon** [comment]
What do you mean by "latest release" exactly?

It does not happen in my test world with these versions:
* OptiFabric 1.9.6
* Optifine 1.16.5 HD U G7
* Tweakeroo 2021-03-16 (should be no changes to that code since 2021-03-03)

**Comment by Dir7y** [comment]
huh, false alarm
i guess i deleted the wrong version when i was updating or something, not having that problem anymore after reinstalling the mod
sorry about that
