### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by itsbumble** [maruohon/tweakeroo#205]
I'm crashing with the latest version of tweakeroo and malilib, I don't know what happened. 

-> crash log https://paste.ee/p/Ne1rm

**Comment by maruohon** [comment]
Looks like a mixin conflict with some other mod. Try with the latest build from here: https://masa.dy.fi/mcmods/client_mods/

**Comment by itsbumble** [comment]
It works with the latest build. I found this to be an issue with Screenshot to clipboard and sheep consistency conflicting, but it only happened when both of them were present, using one of the conflicting mods didnt crash my game, strange.
