### ISSUE TITLE
disableBlockBreakingParticles doesn't work.

### ISSUE THREAD

**Issue by joshuadelin** [maruohon/tweakeroo#207]
The mods I had were
![Capture](https://user-images.githubusercontent.com/81720575/113225011-a8b3ce00-925a-11eb-9155-774b58778b5a.PNG)

**Comment by joshuadelin** [comment]
this is on 1.16.5

**Comment by maruohon** [comment]
Does it not work at all, or do you mean that it still makes those smaller block hitting particles? I just tried with the same set of mods, and the tweak is working for me.

The current implementation just doesn't remove those smaller block hitting particles. The difference when you actually mine blocks is still pretty massive with the actual block breaking particles being gone. I may add an option or possibly a separate tweak later on to also remove the block hitting particles.

**Comment by joshuadelin** [comment]
ah i see i thought that it also removes the particles when hitting it.

I am sorry.
