### ISSUE TITLE
Game crashed with tweakChatPersistentText enable

### ISSUE THREAD

**Issue by B-2U** [maruohon/tweakeroo#240]
as title
tweakChatPersistentText enable 
when pressing Enter if i left some text in chat before
the game would instant crash
disable it or no text left in chatbox then wont happened

**Comment by DanielFallon** [comment]
I can confirm that this happens in version `0.10.0-dev.20210608.211857` and does not happen in `0.10.0-dev.20210614.173711`

This appears to be fixed.
