### ISSUE TITLE
Glitched Ghost Block Sand/Piston

### ISSUE THREAD

**Issue by MinecraftSeaTurtle** [maruohon/tweakeroo#250]
When a sticky piston is powered when it has sand on top, the piston at first doesn't seem to have powered. It makes the extension sound, however, and once it is unpowered, the sand breaks and the piston is stuck in the extended position. The piston does not have a hitbox, but can be collided with. It seems to fix when I reload the world, but when I tried something slightly different (with a slime block inbetween the sand and piston), it did not fix, but became invisible.
![2021-07-08_21 36 30](https://user-images.githubusercontent.com/87160906/125020378-f9934980-e035-11eb-9812-f64a48579548.png)
![2021-07-08_21 36 45](https://user-images.githubusercontent.com/87160906/125020382-fb5d0d00-e035-11eb-84f7-7745c149f493.png)
![2021-07-08_21 37 08](https://user-images.githubusercontent.com/87160906/125020384-fc8e3a00-e035-11eb-8e20-bd747e9b962c.png)
![2021-07-08_21 38 54](https://user-images.githubusercontent.com/87160906/125020392-ff892a80-e035-11eb-87bc-59df9fecac13.png)
![2021-07-08_21 49 31_2](https://user-images.githubusercontent.com/87160906/125020658-7e7e6300-e036-11eb-876e-f8fad493ad8d.png)

The latest (at the time I wrote this) versions of maLiLib and Tweakeroo were used, and I tried it with just maLiLib and in vanilla, neither had any issues. The block below on the last picture is just so I could find it again.

**Comment by maruohon** [comment]
Do you have `noTileEntityTicking` enabled? Other than that I don't see how anything in Tweakeroo would break that...

**Comment by MinecraftSeaTurtle** [comment]
I checked all of the Tweakeroo config options before creating this issue, but for some reason disableTileEntityTicking was enabled, and somehow I missed it... Turning it off fixed it; thanks for the help, and sorry for the trouble!
