### ISSUE TITLE
Tweakeroo not working (1.16.5)

### ISSUE THREAD

**Issue by Cyanah** [maruohon/tweakeroo#258]
I recently downloaded Tweakeroo for 1.16 and tried to place blocks using the FlexibleBlockPlacement and AccurateBlockPlacement. For some reason none of the buttons seem to work, I've tried only using Tweakeroo, which didn't fix the issue. I tried adding Carpet and Carpet Extra to fix it, also nothing. I tried looking up for a fix online and found 1 person who also had the same issue in this Github, but the only fix that was told was using the latest version, which I tried to use multiple versions and got nothing. I have a video where I try to press all 4 buttons to show what my issue is and a screenshot of all the mods I'm currently using. Please let me know if there's anything else I need to provide with logs or settings.

[https://gyazo.com/ccf943e044fda135734421068b9e1dc8](url)

https://user-images.githubusercontent.com/22920656/129483500-759f1dfa-3c18-41d7-877b-f99d7d0829a0.mp4

**Comment by maruohon** [comment]
Did you also enable the tweaks in the Tweak Toggles category? You should enable the corresponding `tweakAccurateBlockPlacement` and `tweakFlexibleBlockPlacement` tweaks, and then you also need the `carpetAccuratePlacementProtocol` option enabled (currently in Tweak Toggles) for the rotations to work for most blocks.

**Comment by Cyanah** [comment]
Ty so much! The issue was that tweakAccurateBlockPlacement and tweakFlexibleBlockPlacement weren't enabled for me, but now they both work as intended!
