### ISSUE TITLE
Error when I try to run Tweakeroo with some other mods. 1.14.4 w/fabric on MultiMC

### ISSUE THREAD

**Issue by Sarelth** [maruohon/tweakeroo#26]
This is the crash log I got and I could not track it down to exactly which mods were interacting funny. 

[crash-2019-11-02_09.37.30-client.txt](https://github.com/maruohon/tweakeroo/files/3800946/crash-2019-11-02_09.37.30-client.txt)

This is the modlist - 
- Autofish 0.8.4
- Chunkborders 0.4.1
- I am Very Smart 1.5.0+1.14.4
- Item sorter 0.15.0-dev.20190806.191755
- Light Overlay 3.6.1
- litematica 0.0.0-dev.20191018.224806
- MaLiLib 0.10.0-dev
- mamiyaotaru folder
- MiniHud 0.19.0-dev.20191007.003640
- Mod Menu 1.7.10+build.119 for 1.14.4
- NarratorBind 1.0.1+build.2
- NBT Tooltip mod 0.3
- optifine (not sure build number)
- Shulker Box tooltip 1.3.1+1.14.4
- Tooltip Autowrap 1.0.0
- Tweakeroo 0.9.10 and 0.10.0-dev.20190905.022216
- Voxelmap 1.9.13

**Comment by Sarelth** [comment]
Newer log. And I may have found the culprit. Looks like I might not have cleared out an earlier modpack fully when I set up this one. And a new instance of it works fine, but the current one is borked, just with Tweakeroo though.

[crash-2019-11-02_15.40.55-client.txt](https://github.com/maruohon/tweakeroo/files/3800972/crash-2019-11-02_15.40.55-client.txt)

**Comment by vacla** [comment]
it is a conflict with a mixin between tweakeroo and a mod from deftware

**Comment by maruohon** [comment]
Does this build fix the crash? https://masa.dy.fi/tmp/minecraft/mods/tweakeroo/tweakeroo-fabric-1.14.4-0.10.0-dev.20191103.001700.jar

**Comment by Sarelth** [comment]
Will test right away. Was eating dinner.
