### ISSUE TITLE
Wiggeling Problem while double-W sprinting

### ISSUE THREAD

**Issue by marcell1no** [maruohon/tweakeroo#265]
So I have this weird bug, whenever I try to sprint with the double-W, my screen starts shaking very fast and I sprint for a short duration and then just stop sprinting and walk normally.

It's caused by Tweakeroo, I de-installed and reinstalled it twice to confirm this.

Very strange, tested all the tweakeroo settings and it doesn't help.

Video Link: https://youtu.be/a7zLi8q7Se4

well, help pls!

**Comment by maruohon** [comment]
I have never seen that before... You don't have the `disableDoubleTapSprint` option enabled? Does sprinting via Ctrl still work normally? Does this happen both in single player and on (all) servers?

**Comment by marcell1no** [comment]
Hm I cant get it to bug on other server or singleplayer.

So whats wrong with my papermc server?
And why is it only buggy when tweakeroo installed?

Plugins installed on my papermc server are
- drivebackupV2
- dynmap

**Comment by maruohon** [comment]
I have no idea... Do you have any Tweakeroo features enabled that might affect this? If you rename the config file (at `.minecraft/config/tweakeroo.json`, do it while the game is not running) to get a fresh default settings config, does it still happen?

**Comment by marcell1no** [comment]
oh well, it just started even without tweakeroo installed, so thats not the issue.
Thanks for your help.

**Comment by maruohon** [comment]
A similar issue has been a long standing vanilla issue for years. I think it's some kind of de-sync in what the server and client think the sprinting state of the player is. AFAIK using the sprint button (by default Ctrl) instead of double-tapping W should not cause this issue.
