### ISSUE TITLE
Stopped Working

### ISSUE THREAD

**Issue by nysquidz** [maruohon/tweakeroo#273]
So the other day I booted MC and Tweakeroo had stopped working.  Couldnt use any of my hotkeys, couldnt accurately place blocks, no response from the mod.  I went and checked to see if there was an update to any of my mods but there wasnt.  I then checked through Mod Menu if the mod was loading and it is.  Through mod menu I can access the Tweakeroo configs but nothing else.  Anyone know a fix?

**Comment by maruohon** [comment]
Did your Tweakeroo configs get reset? Is it just the tweak toggle hotkeys not working, or also the activation keys such as for example the flexible placement offset key (which by default should allow extra keys to be held as well)?

**Comment by nysquidz** [comment]
The tweak toggle and the activation keys such as the invisble shift one arent working either

**Comment by maruohon** [comment]
Check that you still have all the hotkeys set like they are supposed to. Then you can use the `keybindDebugging` option in malilib configs to see if any keys are constantly detected as being pressed. Also check that you haven't somehow added some keys to the `ignoredKeys` config in malilib that are not supposed to be there.

**Comment by nysquidz** [comment]
How do i open up malilib configs?

**Comment by maruohon** [comment]
Either `A + C` or via Mod Menu.

**Comment by nysquidz** [comment]
Ok thanks

**Comment by nysquidz** [comment]
That was it!  No clue how those keys were ignored but they were!  I have one other problem now, i cant open chests with an item in my hand...

**Comment by maruohon** [comment]
Do you have the fake sneak placement tweak enabled? Go through all your tweak toggles and check that you don't just have a bunch of random stuff enabled, as many of the features can cause "weird issues" if you are not aware of them being enabled and basically changing expected vanilla behavior.

**Comment by nysquidz** [comment]
I restarted game and it fixed it ty so much for help :)
