### ISSUE TITLE
I am playing in 21w41a but I think gamma overide is on?

### ISSUE THREAD

**Issue by SietseDeWolff** [maruohon/tweakeroo#280]
![2021-10-18_17 05 09](https://user-images.githubusercontent.com/83921752/137759239-ac8259a0-e559-42a5-94fa-4cad655ef2d7.png)
this is in 21w41a without fabric and tweakeroo ^
 
 
![2021-10-18_17 07 13](https://user-images.githubusercontent.com/83921752/137759318-00ab05bc-4f52-4410-8f5f-5a8a3d8900f3.png)
and this is normal 1.17.1 with fabric and tweakeroo ^

**Comment by maruohon** [comment]
Check the vanilla brightness setting. That's the value that the gamma override tweak changes. Other than that, without the mod installed it can't be the mod's fault if the game is too bright.

**Comment by SietseDeWolff** [comment]
after a few tries and multiple restarts its fixed.

**Comment by SietseDeWolff** [comment]
> Check the vanilla brightness setting. That's the value that the gamma override tweak changes. Other than that, without the mod installed it can't be the mod's fault if the game is too bright.

yes that might be it. thank you
