### ISSUE TITLE
Suggestion: Chat Translate function

### ISSUE THREAD

**Issue by RoyDubnium** [maruohon/tweakeroo#288]
My suggestion is that a feature is added where you can automatically translate incoming and outgoing chat messages independently of each other. For example, you could automatically translate all messages sent by other players into English, while simultaneously translating all outgoing messages to, say, Spanish. With other people's messages, it should also display the original message along with the translated one. Currently, the only up-to-date fabric mod for 1.17 that I could find capable of doing this was Wurst client, which would be inappropriate to have installed on servers.

**Comment by maruohon** [comment]
I'm closing this, as this is now also discussed at https://github.com/maruohon/tweakeroo/discussions/289 with an explanation of why it won't come to Tweakeroo, but rather another mod.
