### ISSUE TITLE
Unable to use Tweakeroo keybinds with Iris shaders active.

### ISSUE THREAD

**Issue by A-noximous** [maruohon/tweakeroo#290]
Recently I tried to take some screenshots using shaders and freecam, but I was unable to use _any_ of Tweakeroo's keybinds with shaders active. Disabling them fixed the issue. Fabric 1.17.1. I used Iris+Sodium for the shaders(Complementary if it matters). A bug?

**Comment by maruohon** [comment]
I have no idea what would cause that in the shaders. Most of the hotkeys by default don't allow any extra keys to be pressed though, unless you allow it via the "Advanced Keybind Settings" widget that is next to each hotkey config button. Sometimes if you for example Alt + Tab out of the game, the game might not see the key release event for Alt and/or Tab, so it would think the key is still down, unless you press it again. There is a `keybindDebugging` option in the malilib configs (`A + C`, or via the settings button in Mod Menu) that you can use to see what malilib sees as being pressed or held.

**Comment by A-noximous** [comment]
Sorry for the late update, but I ran into more issues with iris and I wasn't able to launch the game with the current version(1.1.3) of Iris and had to wait for the update, however after the update this issue no longer exists. Still, thanks for the debugging tip, it helps when i tab out.
