### ISSUE TITLE
swap full durability item

### ISSUE THREAD

**Issue by spyvingen** [maruohon/tweakeroo#294]
I'm on a server where we go through a lot of tools when digging.
So when going to xp farm you have a couple of shulkers with tools that needs mending. 

So my idea is that there should be a tweak that when enabled it swaps a full durability tool to a non full durability to be able to afk mend all the tools you got.

Thanks for a great mod i couldn't live without it :)

**Comment by 5knnbdwm** [comment]
Hey yes there is a repair mode. It is called `tweakRepairMode`. Switches any tool in your inventory that has mending to the active slot to be repaired. Dont think that it switches tools that are in chests tho.

**Comment by spyvingen** [comment]
Ohh nice had no idea thanks.
