### ISSUE TITLE
cannot right click on log when I use 1.17 config file

### ISSUE THREAD

**Issue by ShinhuPark** [maruohon/tweakeroo#305]
[tweakeroo.txt](https://github.com/maruohon/tweakeroo/files/7780074/tweakeroo.txt)
Config file I used(changed extension from json to txt

I replaced 1.18 Tweakeroo config file with 1.17 config file I've used before, then everything was okay except I couldn't strip log even if the FakeSneakingPlacement was off. I can still open chests or hopper but I cannot right click on log. 

Is this because I used old config file?

**Comment by maruohon** [comment]
Answered in #304.

>Is this because I used old config file?

Depends when you (accidentally?) enabled that feature (ie. if it was in the old config already).
