### ISSUE TITLE
hold attack is not working

### ISSUE THREAD

**Issue by sket0714** [maruohon/tweakeroo#31]
version:  tweakeroo-fabric-1.15.2-0.10.0-dev.20200121.202418
while hold attack enable, is doing nothing

**Comment by vacla** [comment]
did you toggle it with hotkey?

**Comment by maruohon** [comment]
The Hold Attack and Hold Use tweaks should be enabled with a hotkey combination that includes the attack or use key, respectively. Otherwise the action will not properly activate/deactivate, unless you then separately click once after toggling the tweak. I can probably fix this though...

**Comment by sket0714** [comment]
i toggle it in gui, the hold use tweak do function, but the hold attack tweak doesnt have any effect. But could i try to work around with periodic attack tweak.
