### ISSUE TITLE
Freecam lightspeed bug

### ISSUE THREAD

**Issue by ZigiPZ** [maruohon/tweakeroo#333]
My tweakeroo free cam started going light speed. Since then everytime I open mc with tweakeroo it crashes. I'm assumming its beacaues I changed creativeflyingspeed on carpet to 10.

**Comment by maruohon** [comment]
What mod version are you using? There was a "light speed" bug in one of the 1.18.1 versions I think, which was fixed in a later release.

**Comment by ZigiPZ** [comment]
tweakeroo-fabric-1.18.1-0.12.0

**Comment by maruohon** [comment]
Looks like it was fixed in 0.12.1. So just update to the latest version (currently 0.12.3) and see if it's fixed.

**Comment by ZigiPZ** [comment]
It still freezes on joining world screen.

**Comment by maruohon** [comment]
Free Camera should get disabled every time you leave a world though. Does it still freeze if you move out Tweakeroo from the mods folder? In that case it would be something else. Did your player somehow get zoomed into some far distance?

**Comment by ZigiPZ** [comment]
Everytime I add tweakeroo to mods folder mc freezes on joining world screen. And yes when I press p ( my shortcut key for freecam) and pressed W it went 10000000000 blocks away.

**Comment by ZigiPZ** [comment]
The same problem as this guy https://github.com/maruohon/tweakeroo/issues/325

**Comment by maruohon** [comment]
Even in the 0.12.3 version? Open the config file at `.minecraft/config/tweakeroo.json` and search for `tweakFreeCamera` and set it to `false` if it's currently set to `true`. If that's not the case, then try renaming the config file (or deleting if you don't care about it) and see if you can then join.

**Comment by ZigiPZ** [comment]
where do I find .minecraft/config/tweakeroo.json

**Comment by ZigiPZ** [comment]
Yes, now it works. Thank you so much.
