### ISSUE TITLE
"accurateBlockPlacement" not working correctly

### ISSUE THREAD

**Issue by spiiross** [maruohon/tweakeroo#335]
Hello,
I found this issue in 1.18.2 version of tweakeroo. So when you place a block ( ex: piston )  facing left with accurate block placement ![2022-03-04_20 55 43](https://user-images.githubusercontent.com/39162894/156834387-b413809a-111a-44aa-9017-e88b9ccd6564.png) then right click again the block will face the player as if i placed it normally
![2022-03-04_20 55 47](https://user-images.githubusercontent.com/39162894/156834545-cdc3f96c-666d-43f1-ac5d-c03196aa8e68.png)
, also when you do the same as the first time and then right click it with different slot the block disappear as if it was a ghost block
![2022-03-04_20 56 19](https://user-images.githubusercontent.com/39162894/156834615-8c26318a-a55a-443c-a7d8-4a64f7fbe2a1.png)
. one more thing is this function keep spamming in the logs "UseItemOnPacket".

**Comment by maruohon** [comment]
I assume you are on some Spigot/Paper server? Then the blocks rotations simply won't work at least in the current mod version. There will probably be a fallback mode of spoofing the player rotation later on to make it work at least for some blocks. No ETA on that though.

**Comment by spiiross** [comment]
The server i'm currently using is fabric and when i play on the server, same thing happens. as for the test ( the pictures ) was in fabric single player world with only tweakeroo installed and nothing else.
![S1](https://user-images.githubusercontent.com/39162894/156843312-732b8106-0155-4e89-a06a-f6bb07a0e882.PNG)

**Comment by maruohon** [comment]
It should definitely work in single player if you have the relevant configs enabled. On a server the server would need to have CarpetExtra in addition to FabricCarpet, and then the `accurateBlockPlacement` rule enabled.

![image](https://user-images.githubusercontent.com/2331050/156845175-0ff623be-e090-4422-8bde-239cd8acab01.png)

![image](https://user-images.githubusercontent.com/2331050/156845195-d439de97-878a-45c0-8333-d2b0734387a8.png)

**Comment by spiiross** [comment]
The config is not the issue .I have changed the fabric loader to a lower version , upgraded fabricAPI to newer version and nothing changed. could you tell me the versions you are using , probably a fabric issue ?
also i noticed this 
![2022-03-04_23 23 50](https://user-images.githubusercontent.com/39162894/156850711-a12ae2de-5423-42b5-b59a-89767079520c.png)
 the accurate block placement doesn't create block update ? ( right piston was placed normally )

**Comment by maruohon** [comment]
Oh you are right... it's actually broken now in 1.18.2. Well that's just great... I didn't even check it that closely as this has never been an issue before, I just placed a few blocks in single player and saw them rotate normally (or so I thought), and didn't even notice they are now ghost blocks.

**Comment by spiiross** [comment]
True, I've been using this mod since 1.16 and never had this issue before. Well, thank you for your time and wish you all the best!

**Comment by maruohon** [comment]
I uploaded version 0.13.1 which fixes this for single player. The same fix will also need to go to the server-side mods that implement the `accurateBlockPlacement` protocol (such as CarpetExtra and QuickCarpet).

**Comment by spiiross** [comment]
Thank you again for your hard work. 👍

**Comment by spiiross** [comment]
Sorry for this but the multiplayer side not working ,unless it's a CarpetExtra issue ? ( I have carpet-extra-1.18.2-pre2-1.4.64 ).
