### ISSUE TITLE
no hotkeys

### ISSUE THREAD

**Issue by Vosjedev** [maruohon/tweakeroo#342]
tweakeroo works fine on lauch, but after 3 minutes, it does not listen to any hotkey anymore. i can still open the x+c menu via mod menu, but all hotkeys i set dont work. they dont reset, just dont work. and then i need to restart the game. i am using some more mods, heres a list

[CIT Resewn](https://citresewn.shcm.io/)
[essensial container](https://essential.gg)
[Fabric API](https://fabricmc.net/)
[KronHUD](https://www.curseforge.com/minecraft/mc-mods/kronhud)
[LambDynamicLights](https://www.curseforge.com/minecraft/mc-mods/lambdynamiclights)
[phosphor,sodium,Lithium](https://jellysquid.me/projects/)
[MaLiLib](https://www.curseforge.com/minecraft/mc-mods/malilib)
[Mod Menu](https://minecraft.curseforge.com/projects/modmenu)
[Not Enough Crashes](https://www.curseforge.com/minecraft/mc-mods/not-enough-crashes)
[Ok Zoomer](https://modrinth.com/mod/ok-zoomer)
[perspective mod redux](https://www.curseforge.com/minecraft/mc-mods/perspective-mod-redux)
[SlotLock](https://www.curseforge.com/minecraft/mc-mods/slotlock)
[Tweakeroo](https://www.curseforge.com/minecraft/mc-mods/tweakeroo)
[wthit](https://www.curseforge.com/minecraft/mc-mods/wthit)
[Xaero's Minimap](https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap)
[Xaero's World Map](https://www.curseforge.com/minecraft/mc-mods/xaeros-world-map)

why does this happen?

i am using a fabric instance using multimc.
i only play servers, and this problem happens on every server i play.

[this is a link to my multimc instance](https://drive.google.com/file/d/15lpQozqGMJISJ7zVa9MmjiDnPH5muR8S/view?usp=sharing)

hope jou can fix this...

**Comment by maruohon** [comment]
You are most likely hitting the "some key getting stuck" issue.

See here for the explanation and "fix": https://github.com/maruohon/malilib/issues/80
