### ISSUE TITLE
Freecam renders caves strangely when inside blocks

### ISSUE THREAD

**Issue by Christorob** [maruohon/tweakeroo#356]
![image](https://user-images.githubusercontent.com/69626244/173419647-e3a9439f-0434-4f92-9dfa-f21185ae09b2.png)
![image](https://user-images.githubusercontent.com/69626244/173419759-2d7424fd-0b04-481a-85e3-5a9ff24f7206.png)
![image](https://user-images.githubusercontent.com/69626244/173419923-4d4ec683-aef2-4dee-84cd-19d0ae7d2beb.png)

Essentially, freecam renders the outside of blocks when underground.

**Comment by maruohon** [comment]
The Free Camera should use basically the same rendering as spectator mode. Or is this different somehow?
