### ISSUE TITLE
FreeCamera Player Inputs not working (1.19.1)

### ISSUE THREAD

**Issue by WickedNush** [maruohon/tweakeroo#362]
Hello Masa,

I am having issues with the free camera and the player inputs when I have them set to true... while in freecam the player inputs are not working when I move the cam away from the player. I believe the game is thinking the crosshair on the freecam is actually the players crosshair; as when I move the camera close to the player he will start attacking if the camera crosshair is in range of whatever mob I am looking at; but when I move away to observe the farm he stops attacking. Thanks for any help
generic > freecameraplayerinputs >true/false (this is set to true)

**Comment by maruohon** [comment]
Seems to work normally for me. Maybe it's a conflict with some other mod? And are you using the 0.14.2 version that is now on CurseForge or one of the earlier builds?

![2022-08-02_23 06 57](https://user-images.githubusercontent.com/2331050/182463818-eaa1b5da-9571-4212-879f-18cd97b46600.png)

**Comment by WickedNush** [comment]
You are right. Sorry. I don't normally try to post issues unless I troubleshoot it myself... it was the FVT fabric mod that conflicted that I recently installed... removed and all is fine. Thanks for the quick help!
