### ISSUE TITLE
The sound effect of nether portal plays multiple times on entering it.

### ISSUE THREAD

**Issue by Wst-04d12** [maruohon/tweakeroo#363]
With the function of DISABLE_NAUSEA_EFFECT and DISABLE_NETHER_PORTAL_SOUND on, this issue happens just right after the local player stand into a portal.
The issue is probably located in mixin.MixinClientPlayerEntity at method disableNauseaEffectPost.

**Comment by AllThePinq** [comment]
For me, this issue occurs regardless of the state of DISABLE_NETHER_PORTAL_SOUND and only occurs when DISABLE_NAUSEA_EFFECT is enabled.

**Comment by maruohon** [comment]
This is now fixed in the 0.14.3 release for MC 1.19.2 (which also works on 1.19.1).
