### ISSUE TITLE
Conflict with Optifine

### ISSUE THREAD

**Issue by ClemFR** [maruohon/tweakeroo#37]
Incompatible with custom Optifine/Optifabric mod in 1.15.2, Game crash at launch

**Comment by vacla** [comment]
@ClemFR Have you tried using optifabric-1.0.0-beta3, also do you have malilib installed?

**Comment by CGDoctor8** [comment]
I have the same issue and i do have beta3 installed
Crashlog
https://paste.ee/p/ahizl

**Comment by ClemFR** [comment]
> 
> 
> @ClemFR Have you tried using optifabric-1.0.0-beta3, also do you have malilib installed?

I have optifabric and malilib to install with the latest version

**Comment by ItzTobias** [comment]
My Game crashes too when Optifabric and Tewakeroo are installed

**Comment by ItzTobias** [comment]
It works again!
Mods:

- optifabric-1.0.0-**beta4**
- preview_OptiFine_1.15.2_HD_U_G1_**pre4**
- tweakeroo-fabric-1.15.2-0.10.0-**dev.20200218.005021**

**Comment by maruohon** [comment]
Closing this as the conflict has been fixed in the latest versions.
