### ISSUE TITLE
Minecraft 1.19.2 crashing with tweakeroo and no view bobbing mod

### ISSUE THREAD

**Issue by Celesian** [maruohon/tweakeroo#370]
My mod config on Minecraft 1.19.2 with the fabric loader 0.14.9:
- malilib 0.13.0
- tweakeroo 0.14.3
- [viewbobbingmod](https://www.curseforge.com/minecraft/mc-mods/no-screen-bobbing) 1.3

What happens:
When i add tweakeroo to this mod list (Minecraft 1.19.2, malilib 0.13.0, no screen bobbing 1.3 on the fabric loader) my game crashes: https://paste.ee/p/tyUdN

**Comment by maruohon** [comment]
It's a conflict between ViewBobbingMod's and Tweakeroo's implementation for "no view bobbing". So then the question is do you need the ViewBobbingMod at the same time, since Tweakeroo has an option to do the exact same thing (Yeets -> `disableWorldViewBob`)?

**Comment by Celesian** [comment]
ah thank you i didn't know tweakeroo had this tweak.
