### ISSUE TITLE
Flexible Block Placement Offset and Flexible Block Placement Rotation not working

### ISSUE THREAD

**Issue by dignansout** [maruohon/tweakeroo#371]
When i press my hotkey to activate any of the flexible block placement tweaks it results me with nothing, no overlay on the blocks or what its supposed to do. I have accurateBlockPlacement set as true, ive been trying to fix this for a while but cant seem to find the soulution.

**Comment by ghost** [comment]
do u also have "TweakFlexibleBlockPlacement" on?

**Comment by dignansout** [comment]
I do but it was an incompatibility with my mod set. I removed some mods and it works fine now

**Comment by ghost** [comment]
alright sounds good. what mod was it however?
