### ISSUE TITLE
Accurate Block placement not working 1.19.2

### ISSUE THREAD

**Issue by Senorloanshark** [maruohon/tweakeroo#378]
when using accurate block placement in the 1.19.2 version as well as the center block offset (the one that floats) the block "places" and then immediately disappears.
I tested this on a server I was running with the latest version of carpet installed

**Comment by maruohon** [comment]
The server needs also the CarpetExtra extension mod, and then the `accurateBlockPlacement` rule enabled. Without it any rotation requests in 1.18.2 or later will just make ghost blocks. The center region in the offset mode also making ghost blocks is a bug in Tweakeroo, but also fixed/worked around by having the protocol rule enabled on the server.
