### ISSUE TITLE
Block Placement Lag

### ISSUE THREAD

**Issue by Senorloanshark** [maruohon/tweakeroo#379]
in recent time ive been using fast blockplacement with the hotbar randomization and it will work great for about 10 minutes but then i start getting severe lag every time i try to place a block, the lag is often bad enough that with fast block placement set to layer it will misplace a block a y level above

Edit: it appears that even right clicking to eat is causing me lag quite hard. I have tried logging off and back on the server im on and problem persists. I do have 8gb allocated, so unless the problem is that its too much ram (java I swear) i dont think that could be the issue. I cannot seem to reproduce this issue on a single player world, at least not yet.

**Comment by maruohon** [comment]
Is it actually related to some mod features being enabled then at all? And does it start to happen after the same-ish amount of time even if you don't fast place stuff or use the hotbar randomizer in that time?

Off the top of my head I can't think of any reason why those features would cause something like that, and I haven't heard of it reported before. Can you take a look at the memory usage on the F3 screen when this happens? Also the profiler pie chart (when opening the F3 screen while holding Shift) can help you find out what is using most CPU time. You can navigate the chart back and forth by using the number keys shown for each category. This way you can find out which category and sub-category takes the most CPU time when the game is lagging.

**Comment by Senorloanshark** [comment]
This issue has happened to many many times, but i can no longer seem to get it to be reproduced so im just gonna close it for now
