### ISSUE TITLE
Toggle Pathfinding Crashes Minecraft After Updating to 1.19.3

### ISSUE THREAD

**Issue by ChickenNdWaffles** [maruohon/tweakeroo#392]
Title says it all. If I try to turn on toggle pathfinding the game crashes. Didn't used to do that. In addition I'd like to mention that litematica is no longer compatible with baritone for some reason since updating both of them. I stayed in 1.19 for a while because I liked all my mods working together and I liked the sculk catalysts dropping 20 exp. Now that I've finally updated to 1.19.3, I had to update all my mods. I can play with litematica in the mods folder or baritone in the mods folder, but not both. They both work fine, just not together apparently. I also no longer can use continuity because they haven't updated yet, so no more connected glass textures I guess. But every other mod I updated works fine as far as I can tell. Here's a list of the mods I have currently in my mods folder that allows me to launch Minecraft without issues. 

1: either baritone or litematica
2: carpet
3: itemswapper
4: worldedit
5: modmenu
6: fabric-api
7: indium
8: sodium
9: forgetmechunk
10: itemscroller
11: minihud
12: tweakaroo
13: malilib

Once continuity is updated, that'll be in my mods folder too hopefully so I can go back to nice looking glass textures.

Just wanted masa to be aware of the situations I am experiencing after updating from 1.19 to 1.19.3.

**Comment by ChickenNdWaffles** [comment]
Didn't mean to close. Fat-fingered the button due to typing on phone.

**Comment by rycbar0** [comment]
there was a bug in baritone that crashed litematica on game startup this should be fixed in the newest baritone version
