### ISSUE TITLE
[Suggestion] some way to interact with blocks while sneaking

### ISSUE THREAD

**Issue by imyxh** [maruohon/tweakeroo#396]
It would be nice if somehow we could interact with blocks, like open chests or use crafting tables, while sneaking. If not that, then allowing the permanentSneak or regular sneak keybind to work while a chest/table/furnace/etc GUI is open, so we could quickly unsneak and sneak again.

**Comment by maruohon** [comment]
There is an option in Generic -> `permanentSneakAllowInGUIs`

**Comment by imyxh** [comment]
> There is an option in Generic -> `permanentSneakAllowInGUIs`

Yeah, but at least for me, I can't figure out how to make this work for block interactions like crafting table or furnace. It's true that this option allows for sneaking in e.g. the inventory or settings, but if I have permanent sneak on and also allow permanentSneakAllowInGUIs, and I click on a crafting table, it does nothing, or tries to place a block if I'm holding one.

**Comment by maruohon** [comment]
It's vanilla behavior that sneaking bypasses the block interaction, and allows you to place blocks against them. Without checking again to verify, I think that check happens on the server side as well, so there is nothing Tweakeroo could do to bypass that. Your only options are activating permanent sneak after you open the GUI, or using fake sneaking instead. But I think you rather want the actual sneaking effect and not just the not-falling-off-blocks effect that fake sneak gives?

**Comment by imyxh** [comment]
Yeah, I'd like the actual sneaking effect, so I can hide my nametag from my friends. Also mildly useful for deep dark biomes.

I tried activating permanent sneak after opening the GUI but it didn't seem to work? I can test again and see if I can get it working. It would also be nice to have a mode where while in permanent sneak, interacting with blocks rapidly unsneaks and sneaks again. I don't know how tall of an order this is though.

**Comment by maruohon** [comment]
You need to change the advanced settings of the tweak hotkey to have Context Both to be able to use the hotkey also inside GUIs.

**Comment by imyxh** [comment]
Ah, of course, thanks! Closing as this suits my needs but feel free to re-open if you feel like the auto unsneak-and-resneak idea is worth the trouble of implementing.
