### ISSUE TITLE
Tweakeroo, Item Scroller and Litematica randomly stopping to accept hotkeys

### ISSUE THREAD

**Issue by ErikderFreak** [maruohon/tweakeroo#399]
Description:
Randomly after playing some time (at least about 15 min) tweakeroo, Itemscroller and Litematica just stop accepting hotkey inputs.

When and how does it occur:
At completely random times. Sometimes several times in one session, sometimes with days apart.
This occurs with all three mods at the same time. 
Having only one or two installed also produces this. 

How to fix: 
Either restart the minecraft instance or wait and after some random time (5-60 min) it works again.

Other information:
There's no issue opening the mods settings via modmenu and toggles like "Toggle Hold Attack" still keep toggled on when this happens. 
This does not happen with any other mods that have hotkeys.

**Comment by maruohon** [comment]
That usually means you are getting some keys "stuck". That can happen especially if you Alt + tab in and out of the game, as the game (or rather the LWJGL library that handles inputs) and malilib may then miss one of the key release events, so then malilib thinks the key is still being held. Another weirder situation where it has happened for me is if I hold shift and use Mouse Back (Mouse 4), then for some reason Mouse Forward/Mouse 5 would trigger and get stuck on.

Most of the "toggle and trigger" type hotkeys in my mods are by default set to "`Allow Extra Keys = false`, which would prevent them from triggering if malilib thinks there are some other keys being held down than what are in the hotkey combination. Pressing the "stuck" key again once will fix this issue.

For finding out which keys are getting stuck, there is a Debug -> `keybindDebugging` option in malilib configs (`A + C` or via Mod Menu). But to be able to open that config menu when you have a key stuck, you would either need to set that menu hotkey to `Allow Extra Keys = true` beforehand, or use Mod Menu and the config menu button in there to open the config menu. 

If the key usually getting stuck is something you don't use in any hotkeys, then you can also add it to the `ignoredKeys` "fake hotkey" in malilib, and then malilib would completely ignore that key. But if it's a key that you do use, and it often gets stuck and it gets annoying pressing it again to un-stuck it, then you can also change at least some of the most often used hotkeys to simply allow extra keys as well.

I'm still undecided if I want to change all the hotkeys by default to allow extra keys or not, as it would break at least some of my personal hotkey setup, so I wonder if it would also break the hotkey setup for many other users. Then again this keys getting stuck issue is also pretty common.

**Comment by ErikderFreak** [comment]
Thank you for the fast response. This sounds reasonable to be the issue.
Next time it happens I'll check with the debug tool. 

Personally I would keep the default at false, since otherwise it would be too easy to click keybinds by accident.

**Comment by ErikderFreak** [comment]
This worked! 
Strangely enough it's the key "G" which locks up. It's a key I never press. 
But ignoring that key seems to work fine. 
Thank you again
