### ISSUE TITLE
[0.15.0] Freecam interactions not working

### ISSUE THREAD

**Issue by VeryEvilHumna** [maruohon/tweakeroo#417]
Freecam interaction worked for me for a long time, but at one point just stopped (I don't even remember after restarting the game or during the game)

- [x] I tried other worlds
- [x] I tried resetting the config
- [x] I tried restarting my game
- [x] I tried redownloading the mod from curseforge 
- [x] I tried deleting all other mods
- [x] I tried restarting my pc

Vid: https://youtu.be/3ef57O3K2SA

Test modpack for 1.19 contains many mods, i'm too lazy to do another test modpack for showing a feature that works in this version. But including:
- malilib-fabric-1.19-0.12.1
- tweakeroo-fabric-1.19-0.13.3

Test modpack for 1.19.3 contains only:
- malilib-fabric-1.19.3-0.14.0
- tweakeroo-fabric-1.19.3-0.15.0

**Comment by maruohon** [comment]
Based on that video, it was broken in 1.19, and in 1.19.3 it's working correctly. I would suspect some other mod changed things in your 1.19 instance such that the interactions happened from the free camera point of view. You are **never** supposed to be able to interact from the free camera point of view. The block highlight box and the hitting particles appearing from the free camera point of view are still unintended, and I'll try to fix/remove those at some point. But at least it's harmless and just visual.

There is the `freeCameraPlayerInputs` hotkey that allows you to toggle on interactions from the **player's** point of view, while you are in free camera mode. And there is another hotkey for allowing player movement. But the free camera point of view is supposed to be just a non-interacting free moving camera perspective, nothing else.
