### ISSUE TITLE
fastRightClick does not work with shovel/hoe

### ISSUE THREAD

**Issue by DyonR** [maruohon/tweakeroo#424]
Enabling the fastRightClick tweak and attempting to path a dirt-like block it does not work. Same when tilting dirt-like blocks with a hoe. Using default settings.

Reason this would be nice is so you can just hold right click and path or tilt bunch of blocks without the need to manually spam click.

**Comment by maruohon** [comment]
Check that you don't have Fast Block Placement or one of the placement related restriction tweaks enabled. At least FBP takes precedence over fast right click.

**Comment by DyonR** [comment]
I'm at school now, so can't really test at the moment. Will report back later today :)

**Comment by DyonR** [comment]
Yep. You're right. I had Fast Placement on 🤡
