### ISSUE TITLE
1.12.2 tweakeroo is incompatibly with inertia client

### ISSUE THREAD

**Issue by tmuaprep** [maruohon/tweakeroo#433]
im using the 0.10 version from the masa.dy.fi website and it hasn't worked at all. incompatible with kami blue and seppuku too

**Comment by tmuaprep** [comment]
doesn't work with future client either

**Comment by maruohon** [comment]
Sorry, but I don't have time or any interest to try to figure out incompatibilities with some weird anarchy or pvp clients and hacks. Tweakeroo is not meant to be used for hacks and pvp advantage. If it works then I can't stop anyone from using it, but I won't specifically try to fix it to work with other hack mods and clients.
