### ISSUE TITLE
tweakHoldUse and tweakHoldAttack continue after being toggled off

### ISSUE THREAD

**Issue by Coldwire** [maruohon/tweakeroo#44]
Map a hotkey for tweakHoldUse or tweakHoldAttack. Toggle it on and it'll work fine, but when you toggle it off, you'll continue to attack/use until you left/right click. Would be a lot more convenient without the extra step of clicking after toggling off.

Version of MC: 1.5.2
Mods used:
malilib-fabric-1.15.2-0.10.0-dev.20+arne.4
fabric-api-0.5.1+build.294-1.15
tweakeroo-fabric-1.15.2-0.10.0-dev.20200302.214816

**Comment by maruohon** [comment]
I uploaded a new build with the fix for this for 1.12.2 (on my server) and for 1.15.2 (on my server and on CurseForge).
