### ISSUE TITLE
[SUGGESTION] PersistentStackOrganisation, making you not take the last item from a stack, for easier organization

### ISSUE THREAD

**Issue by Mihajlo-Zivanovic** [maruohon/tweakeroo#443]
You know that feeling when you sorted some inventory really well, and you don't want to mess it up, so every time you take something from it you take the full stack, and then return just one item so your organization is still there? Well, I propose a feature, or maybe even a couple features around that concept of "not taking the last item in a stack." Some ideas might be:
1) A toggle that makes it so shift-clicking leaves one item in the stack (except if it is the only one left/unstackables, in all other suggestions this is presumed);
2) A toggle that makes it so restocking not take the last item (very useful if you don't want to clog up your inventory with the pesky seeds or dirt when building, makes that periodic restocking on blocks a breeze);
3) A toggle that makes it so some "specially labeled*" shulkers don't allow taking the last item; ...

Also, this would greatly improve organization of some storages, either in a manual storage system, or if I am to lazy to build a sorter for my iron farm, I can just provide a "template" in the storage chests and easily maintain it by simply not caring. I really feel like it has a lot of potential, as there are probably countless more scenarios where it could be useful that aren't mentioned here.

*this could be encoded in the name, color, some special item (although that might be annoying), ...

**Comment by maruohon** [comment]
Some of these fit a lot better in the Item Scroller mod. And in fact it already has a similar feature: hold shift and **right click** and drag over slots, that will leave one item in each slot.

The restock related options may first appear in the newer cleaned up and rewritten mod main development code in 1.12.2, so they would then come to the later MC versions when that code gets ported. (I'm basically not adding anything new to the old code base at this point anymore. That's basically why there haven't been any new major features in the 1.13+ versions of the client mods in like 2-3 years by now.)

**Comment by Mihajlo-Zivanovic** [comment]
Oh thank you, sorry for wasting your time
