### ISSUE TITLE
Flexible block placement and fast block placement not working. [1.20]

### ISSUE THREAD

**Issue by Felix-Asada** [maruohon/tweakeroo#450]
When I try to use Flexible block placement in my singleplayer world, it does show the grid. But when i want to place a block on the offset, the block is placed on the original block instead of the corner. And same goes for the block rotation.
I have carpet installed, and i have enabled the AccurateBlockPlacement. 

![image](https://github.com/maruohon/tweakeroo/assets/140382452/28c6a0c1-d45d-4f2d-80c2-bb0540e14c26)
![image](https://github.com/maruohon/tweakeroo/assets/140382452/e16e7952-0b9c-442d-8b8d-ea2dee5bc3a5)
![image](https://github.com/maruohon/tweakeroo/assets/140382452/3a75a5b1-9070-431c-b48f-af63317d294d)

**Comment by maruohon** [comment]
Preferably in single player you shouldn't use Carpet's `accurateBlockPlacement` rule, but instead let Tweakeroo handle the placement itself. That would be the Generic -> `clientPlacementRotation` option. But that only affects rotations and other block properties, not the offset feature. If offset isn't working, then I would suspect some mod conflict on the client that prevents any of Tweakeroo's placement related features from working.

**Comment by Felix-Asada** [comment]
I found the mod that made it not work!
it was the clean cut mod. I don't know how and why it makes that so nothing works cause there is like 0 keybinds or stuff linked to the mod (exeppt the use of the left click button).
