### ISSUE TITLE
[Feature Request] HandRestock should still restock when items are consumed by Carpet `/player use` commands

### ISSUE THREAD

**Issue by JacobLiu001** [maruohon/tweakeroo#460]
When the player uses an item through Carpet `/player <name> use continuous`, HandRestock does not do anything, because HandRestock is triggered only when the right mouse button is pressed.

This is observed on tweakeroo version 1.20.1-0.17.1.

It would be helpful if it were to listen to inventory changes instead of right mouse button clicks, thereby enabling the restock to go through even when . 

A possible downside is performance -- if all inventory changes are listened for, it may consume more resources.

**Comment by maruohon** [comment]
I won't change the current restock behavior. But there is a separate tweak "Continuous Hand Restock" currently only in the 1.12.2 code, that basically checks the hand slot every game tick and then tries to re-stock it if it runs out of items. So once that 1.12.2 code gets ported to the later MC versions... For now there was some other mod that ports that feature already, but I can never remember which mod it was. It might be TweakFork, Tweakermore, or MasaAdditions.
