### ISSUE TITLE
Tweakeroo wont work with SBV Epoch Runner modpack

### ISSUE THREAD

**Issue by Ares0564** [maruohon/tweakeroo#469]
Hello there,

I have a problem with tweakeroo in the Epoch Runner modpack. When I open the game and go to mods, where u can configure the config files from ingame, tweakeroo isnt shown as an installed mod. Altough it is installed over the course forge mod launcher, 1.12.2 btw. I love this mod but cant use it sadly. The Gui also does not open at all altough I deleted all X and C keybinds so nothing could interfere. 
When u close a world there is a message about shutting down the internal server. I think it might have something to do with that.

I know that this is propably a typical modpack issue, but my last hope of making this mod work is asking the creator directly.

**Comment by maruohon** [comment]
Which version of Tweakeroo did you install, and from where? If you installed the old `0.9.0` version from CurseForge, then that's 1.) super old and outdated and 2.) for the LiteLoader mod loader.

You would rather want to use the Forge ports of Tweakeroo and malilib, which are currently only on my server, here: https://masa.dy.fi/mcmods/client_mods/?mcver=1.12.2

You will however most likely get some incompatibility issues in a large mod pack with some of Tweakeroo's features. I've had to make some modified versions of the mod jar in the past for some people, by disabling some Mixins (by removing them from the `mixins.tweakeroo.json` file) that conflict with other mods.

Also depending on whether other mods in the pack use Mixins, you may need to use this separate version of malilib without the Mixin library embedded: https://masa.dy.fi/tmp/minecraft/mods/misc_test_versions/malilib-forge-1.12.2-0.10.0-dev.23.nomixin.jar

**Comment by Ares0564** [comment]
Scrennshot of the downloaded tweakeroo mod
![Bild_2023-12-17_173852334](https://github.com/maruohon/tweakeroo/assets/137712712/040f1adc-e613-4fb2-9af7-e07dc7201e90)

Do I need to look up what mixins are to resolve this issue?

**Comment by maruohon** [comment]
That is the LiteLoader version of the mod, it won't work with the Forge mod loader directly.
![image](https://github.com/maruohon/tweakeroo/assets/2331050/e1a30a21-8330-44c6-9521-f97be0a52bdf)

> Do I need to look up what mixins are to resolve this issue?

No, I was just explaining what will probably be the issues at first.

So first just download the malilib and Tweakeroo Forge versions from the page I linked, and put them to the mods directory of your instance. And remove your current Tweakeroo version as it won't do anything. Then try launching the game, and logging in to a world.

If you get a crash either during loading the game, when logging to a world, or when trying to place a block for example, then we need to start dealing with the Mixin conflicts. Which basically means that you send me the crash log, and I make you modified versions of the mod until it stops crashing... and we hope that we don't need to disable too many of the features you actually wanted to use. And in that case it might be easier if you hop on to my Discord server, it's linked on the Tweakeroo CurseForge page.

**Comment by Ares0564** [comment]
Im alredy on ure DC. I will try out if it works with the linked mods. could take some time since restating the modpack takes aeons

**Comment by Ares0564** [comment]
Hello,

sorry for the late report, it was dinnertime.

I imported the linked tweakeroo mod and the second malilib version in cases of alredy existing mixing mods and got a crash while stating the game.

Here is the crash log:
[crash-2023-12-17_17.52.57-client.txt](https://github.com/maruohon/tweakeroo/files/13697311/crash-2023-12-17_17.52.57-client.txt)

And I found mods with mixing in the name, dunno if it helps but here are the file names since i couldnt upload the jar file:
!mixinbooter-4.2
_MixinBootstrap-1.1.0

And this is the link to the modpack if it helps: https://www.curseforge.com/minecraft/modpacks/epoch-runner

**Comment by Ares0564** [comment]
For everyone that reads through this, and has the same problem, this is the final mod version that worked for me together with the link to the malilib library.

MaliLib: https://masa.dy.fi/tmp/minecraft/mods/misc_test_versions/malilib-forge-1.12.2-0.10.0-dev.23.nomixin.jar
tweakeroo: https://masa.dy.fi/tmp/minecraft/mods/misc_test_versions/tweakeroo-forge-1.12.2-0.10.0-dev.20201007.231650%2Boptionalmixinsnoterdmixin.1.jar

**Comment by Ares0564** [comment]
Thanks for the Help.

For everyone that reads through this, and has the same problem, this is the final mod version that worked for me together with the link to the malilib library.

MaliLib: https://masa.dy.fi/tmp/minecraft/mods/misc_test_versions/malilib-forge-1.12.2-0.10.0-dev.23.nomixin.jar
tweakeroo: https://masa.dy.fi/tmp/minecraft/mods/misc_test_versions/tweakeroo-forge-1.12.2-0.10.0-dev.20201007.231650%2Boptionalmixinsnoterdmixin.1.jar
