### ISSUE TITLE
Warning of "Block breaking prevented by Break Restriction" is annoying

### ISSUE THREAD

**Issue by hhxc-0** [maruohon/tweakeroo#471]
The 'tweakBlockTypeBreakRestriction' tweak displays warnings frequently when attempting to break a restricted block. One suggestion is to have the warning appear only once when trying to break the same block, or to include a switch to toggle these warnings.
![屏幕截图 2023-12-20 200916](https://github.com/maruohon/tweakeroo/assets/124414396/f1cb6674-8f82-40b4-9f46-81525e6e81ae)

**Comment by maruohon** [comment]
There is a config for the message type/output at Generic -> `blockTypeBreakRestrictionWarn`.

**Comment by hhxc-0** [comment]
That's good. Thanks for the help.
