### ISSUE TITLE
Update suggestions

### ISSUE THREAD

**Issue by kndxhz** [maruohon/tweakeroo#477]
I hope to add an option where you can press the set shortcut key when the free camera is enabled. But when the set shortcut key is pressed, the player's left and right key data packets can be sent to the free camera object. Note: this is not a switch between player operations!
Example: If I bind the i shortcut key
When I press i, my free camera angle is facing -100 100 100
So at this point, I press the left button and send the left button data packet to the -100 100 100 blocks. Right click is the same.
This is not a cheating feature, but it can make it more convenient for players to build their houses. Sometimes, they may not be able to reach them due to obstructed views, so this feature can be used.
The code is not difficult either, as there are already ready-made open-source mods available for demonstration
https://github.com/MinecraftFreecam/Freecam
As for why I didn't use this mod directly Because I don't want Minecraft, which started very slowly before, to start slower after adding a new mod

**Comment by maruohon** [comment]
The idea of the free camera feature in Tweakeroo is to **only be a camera perspective**. I specifically don't want the player to be able to interact with anything from the free camera point of view.

The only "functionality" you get from the free camera perspective is the looked at block coordinates and info via MiniHUD's info lines, and inventory preview via Tweakeroo's or Litematica's inventory preview features. Those are simply just changing from what point of view those infos are shown.
