### ISSUE TITLE
Stuck in model

### ISSUE THREAD

**Issue by LittlePlumShine** [maruohon/tweakeroo#500]
I'm on a server with Pehkui and Custom Player Models. I decided to mess with the Custom Player Models stuff, and now I am stuck in a model and unable to exit it. This wouldn't be too much of an issue if it didn't make it so I couldn't fit into the spaces I should be able to fit into (I am a smaller size that can fit into one block tall spaces). How do I stop using the model?

**Comment by maruohon** [comment]
I have no idea what you are talking about... how is this related to Tweakeroo?

**Comment by LittlePlumShine** [comment]
I am so sorry, I was on a issues page for Custom Player Models and tried to submit this there. It's my first time using Github, I guess I must have hit a wrong button.

**Comment by maruohon** [comment]
ah, okay, no worries
