### ISSUE TITLE
Add 1.20.1

### ISSUE THREAD

**Issue by Kastle253** [maruohon/tweakeroo#511]
There is 1.20.4 version only, i don't know how to do it in 1.20.1

**Comment by maruohon** [comment]
They are on CurseForge: https://legacy.curseforge.com/minecraft/mc-mods/tweakeroo/files/all?filter-status=1&filter-game-version=2020709689%3A9990

**Comment by Kastle253** [comment]
Ye but i want open source, can you add it?

**Comment by maruohon** [comment]
What do you mean? The code is in this repo. I think the last commit before the 1.20.2 updates is ad558dafe.

**Comment by Kastle253** [comment]
I want the code of 1.20.1 just like the 1.20.x but its set to 1.20.4 and i don't know how to fix that

**Comment by Kastle253** [comment]
I want it to a specific version, not to 1.20.4 but there is only the code for 1.20.4 so i can't use

**Comment by maruohon** [comment]
I told you the commit hash of the last 1.20.1 commit. You can find any older version in the commit history of the relevant branch by looking for the last commit that is before the update to the next MC version or snapshot.

![image](https://github.com/maruohon/tweakeroo/assets/2331050/f6f2ea15-1424-401c-a97c-2cbcb63fd124)

So either use git to checkout that commit in your cloned local repo, or you can also just browse the repo in that commit and download it as zip from GitHub.

**Comment by Kastle253** [comment]
worked, tysm
