### ISSUE TITLE
Bug: Ornithe 1.12.2 Shulker box display causes crash

### ISSUE THREAD

**Issue by Player505** [maruohon/tweakeroo#512]
Using the shulker box display tweak causes the client to crash.
logs: https://mclo.gs/djnmQjE

**Comment by maruohon** [comment]
Ah this is that incompatibility with newer FastUtils versions again...

I uploaded malilib `0.60.1` just now to my server, try if that fixes the crash for you.
Link: https://masa.dy.fi/mcmods/client_mods/

If that fixes it, then I'll upload it to Modrinth as well.

**Comment by Player505** [comment]
Yep its fixed.
Thakn you very much!
