### ISSUE TITLE
unable to press reset button and uneven gui

### ISSUE THREAD

**Issue by Nrazuke** [maruohon/tweakeroo#516]
I cant press the gui button for reset and its uneven is there any fixies for this?

![Screenshot 2024-08-21 225924](https://github.com/user-attachments/assets/7aa9625b-e8c9-42ee-adf1-9afa6feb40d1)

**Comment by maruohon** [comment]
The only "fix" for the current mod versions is to change the vanilla GUI scale setting. The mods are designed for scale 2 (old "Normal") in a 1280x720 window, so a 640x360 effective usable resolution in the GUI.

**Comment by Nrazuke** [comment]
> The only "fix" for the current mod versions is to change the vanilla GUI scale setting. The mods are designed for scale 2 (old "Normal") in a 1280x720 window, so a 640x360 effective usable resolution in the GUI.

alright, thanks for the quick response!
