### ISSUE TITLE
Conflict with Carpet mod

### ISSUE THREAD

**Issue by 0xfeeddeadbeef** [maruohon/tweakeroo#55]
[Carpet](https://github.com/gnembon/fabric-carpet) and Tweakeroo do not play well together:

```
[14:48:00] [main/WARN]: Method overwrite conflict for getPickupDelay in carpet.mixins.json:ItemEntityMixin, previously written by fi.dy.masa.tweakeroo.mixin.MixinItemEntity. Skipping method.
```

It is still possible to load both mods and use _almost_ all features.

(Link to [Carpet issue](https://github.com/gnembon/fabric-carpet/issues/234))

**Comment by maruohon** [comment]
Are you saying some feature actually does not work properly? This is just a warning due to a getter method conflict, both mods should still work fine AFAIK?

**Comment by 0xfeeddeadbeef** [comment]
Sorry, it was a wild guess. At least all the features I'm using are working fine. Also, gnembon fixed this in his carpet mod, so I'm closing the issue now.
