### ISSUE TITLE
Mod not applying properly

### ISSUE THREAD

**Issue by teolicht** [maruohon/tweakeroo#56]
**Minecraft 1.15.2**
tweakeroo-fabric-1.15.2-0.10.0-dev.20200320.230739
malilib-fabric-1.15.2-0.10.0-dev.20+arne.6
fabric-api-0.7.1+build.301-1.15

Hi.
The mod gets loaded properly but none of the features work. When trying out flexible block placement, the overlay does show up but the blocks get placed normally, which they shouldn't. This is in a singleplayer world. Free camera looks completely glitched: https://i.imgur.com/gqkSpbB.png
The Tweakeroo Configs appear to be working fine, I tried some different things there but none of them worked. Any ideas?

**Comment by maruohon** [comment]
"None of them worked"?

Free Camera is known to be broken with Optifine (Fast Render option maybe?).

For Accurate or Flexible placement did you enable the carpet protocol option at the top of Tweak Toggles? It's required even in single player, but it's not really documented anywhere yet. The config GUIs will get a re-do at some point to better organize and document things.

**Comment by teolicht** [comment]
Was about to say Fast Camera conflicts with OptiFine indeed. Fast Render was already disabled in the screenshot actually... Carpet protocol option was disabled, but enabling it didn't actually fix the flexible placement problem. Still has no effect in block placement. Could it be something else?

**Comment by maruohon** [comment]
So assuming you get the Flexible placement overlay, means that the flexible placement tweak itself is working. Then there are two other options that are required for the rotations to work in single player, the first is the above mentioned carpet protocol option, the second is the `clientPlacementRotation` option in Generic (but that should be enabled by default).

Do you also have Carpet mod installed? I'm not sure if I have tested it with Carpet in single player, but it's possible that in that case you also need to enable the `accurateBlockPlacement` rule in Carpet, it might be overriding Tweakeroo's own handling.

**Comment by teolicht** [comment]
Checked what you said. Still not working. I do not have Carpet mod installed. 
Here are some pics: https://imgur.com/a/o9Rn9xv I've left everything in the Generic tab with default settings.

**Comment by maruohon** [comment]
It should work if you get the overlay... 🤔 Which blocks are you trying to place?

**Comment by teolicht** [comment]
I tried many different blocks. It's really weird... Tried in survival and in multiplayer, neither worked. 
I will keep trying

**Comment by maruohon** [comment]
Maybe this will show something you missed?
https://youtu.be/ScWvhwctiNU

**Comment by teolicht** [comment]
I knew it was something ridiculous I was missing. I was using the wrong key - I was pressing left alt thinking it was going to do the offset block placement, when actually the left ctrl key was bound to that. Damn I feel stupid now... everything works fine now. Thank you so much for you help, you video really help clear things up! 😁
