### ISSUE TITLE
Placement restriction not working

### ISSUE THREAD

**Issue by Sorphius** [maruohon/tweakeroo#57]
Am I doing something wrong here?  Placement restriction worked just fine yesterday, now it doesn't even though I enabled it. I have tried restarting my game and switching modes but nothing is working

I have the same problem with Flexible block placement offset even though I'm using the keybind.

Freecam and angle snap work fine tho. Is there an obvious solution That I'm missing?

**Comment by Sorphius** [comment]
Sorry If I haven't included enough information, I am unsure what to include.

**Comment by maruohon** [comment]
The Placement Restriction mode currently doesn't work properly on its own, it only works with the Fast Block Placement feature (and it by default automatically gets enabled when you enable fast block placement). This will get fixed at some point when I have the time to completely rewrite all the placement features related code.

**Comment by Sorphius** [comment]
Thank you for the quick response! This worked great!
