### ISSUE TITLE
It is possible to set zoomFov to 0.

### ISSUE THREAD

**Issue by filipfigzalski** [maruohon/tweakeroo#82]
When zoomFov is set to 0 zooming is broken.

**Comment by maruohon** [comment]
It's just how the vanilla rendering works. It's also broken if you go to 180 or above, or near 360 etc. There is nothing really that can be done to fix this, the zooming would then need to use different type of rendering entirely from just changing the FoV value. Is there a reason you would want to set it to exactly 0? Is 1 or 0.5 or 0.1 not already extremely "close" to the target?

**Comment by maruohon** [comment]
Or I guess you meant that it should not be possible to set it to 0? I could set a lower limit of 0.1 or something I guess...

**Comment by filipfigzalski** [comment]
Yeah that's what I meant. I just think that if it doesn't render, then it shouldn't be possible to set it to 0.
