### ISSUE TITLE
FreeCamera breaks completely with OptiFabric and Optifine

### ISSUE THREAD

**Issue by justahumanperson** [maruohon/tweakeroo#84]
when installing Optifine 1.16 HD Ultra pre2 and also Optifabric 1.1.0 beta, I noticed that FreeCamera does not work anymore. When toggling FreeCamera, the game stops completely until freecamera is disabled.

**Comment by jhmaster2000** [comment]
Attempting to enable the FreeCamera tweak also appears to crash instantly on 1.16 with Sodium

**Comment by maruohon** [comment]
@CheatTriggers Are you using version `0.10.0-dev.20200716.161850`? The two previous builds `0.10.0-dev.20200716.0*` did crash with Sodium, but that latest build should work.

**Comment by maruohon** [comment]
Also @justahumanperson also try if that latest build works with OptiFabric.
It's available here: https://masa.dy.fi/mcmods/client_mods/?mcver=1.16.1

**Comment by MeeniMc** [comment]
It works fine with latest optifine/optifabric/tweakeroo combo, on both 1.16.1 and 1.16.3. You can close IMO.
