### ISSUE TITLE
Setting conflict between map preview and shulker box preview

### ISSUE THREAD

**Issue by jhmaster2000** [maruohon/tweakeroo#85]
For some reason, having map preview enabled also enables shulker box tooltip previews regardless of the shulker box tooltip tweak being strictly set to false, turning off the map preview also turns off shulker box tooltip together with map preview itself.

As someone who only wants map preview from Tweakeroo (since I have Shulker Box Tooltip mod for those, since its considerably better than Tweakeroo's implementation of it, no offense) I find this extremely annoying.

MC version: 1.16.1 (Singleplayer)
Tweakeroo Version: 0.10.0-dev20200630.023405

**Comment by maruohon** [comment]
Well this should simply not be possible. And I certainly can't reproduce this issue.

Or do you mean that other mod disables the vanilla preview text and it comes back with Tweakeroo's map preview, and not Tweakeroo's shulker box preview rendering itself? But I also can't see why Tweakeroo's rendering would affect that.

**Comment by jhmaster2000** [comment]
I can no longer reproduce this on the latest versions, closing.
